#### Q. Print or show only 3 decimal places of the numpy array rand_arr.  

Input:  

rand_arr = np.random.random((5,3))

In [1]:
import numpy as np

In [9]:
rand_arr = np.random.random((5, 3))
new = np.set_printoptions(precision = 3)
print(rand_arr)

[[0.494 0.707 0.094]
 [0.154 0.902 0.549]
 [0.708 0.724 0.098]
 [0.866 0.975 0.765]
 [0.022 0.469 0.091]]


In [11]:
np.round(rand_arr, 3)

array([[0.494, 0.707, 0.094],
       [0.154, 0.902, 0.549],
       [0.708, 0.724, 0.098],
       [0.866, 0.975, 0.765],
       [0.022, 0.469, 0.091]])