#### Convert a 1D array to a 2D array with 2 rows

In [3]:
import numpy as np

In [9]:
arr_1D = np.arange(9)
arr_2D = arr_1D.reshape(3, -1)
print(f'1D:\n{arr_1D}')
print(f'\n\n2D:\n{arr_2D}')

1D:
[0 1 2 3 4 5 6 7 8]


2D:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
