####  Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)  
b = np.repeat(1, 10).reshape(2,-1)  
Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],  
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
import numpy as np

In [12]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

Method 1: Concatenate

In [25]:
np.concatenate((a, b), axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Method 2: hstack

In [32]:
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])