In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 10).reshape(3, 3)

In [11]:
arr[0]

array([1, 2, 3])

In [17]:
print(arr[0], arr[1], arr[2])

[1 2 3] [4 5 6] [7 8 9]


In [19]:
print(arr[:, 0], arr[:1], arr[:,2])

[1 4 7] [[1 2 3]] [3 6 9]
