In [5]:
import numpy as np

In [7]:
arr1 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

write a command to concatenate arr1 and arr2 both rowwise and columnwise

1. row

In [13]:
np.concatenate((arr1, arr2), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

2. Columnwise

In [16]:
np.concatenate((arr1, arr2), axis = 1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

Result of np.hstack(arr1, arr2)

In [21]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])