#### Array slicing

In [2]:
import numpy as np

In [6]:
A = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

Find:


In [9]:
B[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [11]:
A[2:6:3]

array([30, 60])

In [19]:
A[-1:-3]

array([], dtype=int32)

In [23]:
B[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [25]:
B[:3, 2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])