### Problem 1: Array Creation and Basic Operations
Create a 1D NumPy array with numbers from 10 to 50 (inclusive) with a step of 5. Then:
1. Find the mean and standard deviation
2. Create a boolean mask for values greater than 30
3. Replace all values greater than 30 with -1

In [1]:
import numpy as np

In [2]:
arr = np.arange(10, 51, 5)
print(f"Array: \n{arr}")

mean = np.mean(arr)
std_dev = np.std(arr)

print(f"Mean: {mean}")
print(f"Standard deviation: {std_dev}")

mask = arr > 30
arr[mask] = -1

print(f"Array: \n{arr}")

Array: 
[10 15 20 25 30 35 40 45 50]
Mean: 30.0
Standard deviation: 12.909944487358056
Array: 
[10 15 20 25 30 -1 -1 -1 -1]


### Problem 2: 2D Array Manipulation
Create a 6x6 matrix filled with random integers between 1 and 100. Then:

1. Extract the 3x3 submatrix from the center
2. Find the sum of each row
3. Find the maximum value in each column

In [3]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(1, 100, size = (6, 6))
orginal_arr = arr.copy()
print(f"Original array: \n{orginal_arr}")

# Sorry I extracted 4x4 submatrix. 3x3 seems inappropriate
submatrix = arr[1:5, 1:5]
print(f"4x4 center submatrix: \n{submatrix}")

# Sum of each row
total_row = np.sum(arr, axis = 1)
print(f"sum of each row: {total_row}")

# The maximum value in each column
max_col = np.max(arr, axis = 0)
print(f"The maximum of each column: {max_col}")

Original array: 
[[52 93 15 72 61 21]
 [83 87 75 75 88 24]
 [ 3 22 53  2 88 30]
 [38  2 64 60 21 33]
 [76 58 22 89 49 91]
 [59 42 92 60 80 15]]
4x4 center submatrix: 
[[87 75 75 88]
 [22 53  2 88]
 [ 2 64 60 21]
 [58 22 89 49]]
sum of each row: [314 432 198 218 385 348]
The maximum of each column: [83 93 92 89 88 91]


### Problem 3: Array Reshaping and Indexing
Create a 1D array with values from 1 to 24. Then:

1. Reshape it into a 4x6 matrix
2. Extract every 2nd row and every 3rd column
3. Flatten it back to 1D using two different methods

In [4]:
import numpy as np
arr = np.arange(1, 25).reshape(4, 6)
orginal_arr = arr.copy()
print(f"Orginal array: \n{orginal_arr}")

# Extract every 2nd row and every 3rd column
sub = arr[::2, ::3]

print(f"every 2nd row and every 3rd column: \n{sub}")


# Flatten it back to 1D using two different methods
flatten_copy = arr.flatten()
ravel_view = arr.ravel()

print(f"copy: {flatten_copy}")
print(f"view: {ravel_view}")

Orginal array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
every 2nd row and every 3rd column: 
[[ 1  4]
 [13 16]]
copy: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
view: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


### Problem 4: Broadcasting Challenge
Create two arrays:

1. Array A: shape (4, 1) with values [1, 2, 3, 4]
2. Array B: shape (3,) with values [10, 20, 30]
3. Add these arrays together using broadcasting and explain the resulting shape.

In [5]:
import numpy as np
A = np.array([[1], [2], [3], [4]])
B = ([10, 20, 30])
print(f"A + B: \n{A + B}")

A + B: 
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


### Problem 5: Statistical Analysis
Create a 2D array (5x4) with random normal distribution (mean=50, std=15). Then:

1. Calculate the mean along axis 0 and axis 1
2. Find the overall standard deviation
3. Normalize each column to have mean=0 and std=1

In [6]:
import numpy as np
np.random.seed(42)
arr = np.random.normal(loc = 50, scale = 15, size = (5, 4))
original_arr = arr.copy()
print(f"Original array: \n{original_arr}")

#  The mean along axis 0 and axis 1
mean_axis0 = np.mean(arr, axis = 0)
mean_axis1 = np.mean(arr, axis = 1)

print(f"Mean along axis 0: {mean_axis0}")
print(f"Mean along axis 1: {mean_axis1}")

# overall standard deviation
std_dev = np.std(arr)
print(f"Overall standard deviation: {std_dev}")

# Normalize each column to have mean=0 and std=1
nor_arr = (arr - np.mean(arr, axis = 0))/np.std(arr, axis = 0)
print(f"Normalized arr: \n{nor_arr}")

Original array: 
[[57.4507123  47.92603548 59.71532807 72.84544785]
 [46.48769938 46.48794565 73.68819223 61.51152094]
 [42.95788421 58.13840065 43.04873461 43.0140537 ]
 [53.62943407 21.30079633 24.12623251 41.56568706]
 [34.80753319 54.71370999 36.37963887 28.81544448]]
Mean along axis 0: [47.06665263 45.71337762 47.39162526 49.5504308 ]
Mean along axis 1: [59.48438092 57.04383955 46.78976829 35.15553749 38.67908163]
Overall standard deviation: 14.03579938340667
Normalized arr: 
[[ 1.30126067  0.17103052  0.70570266  1.49000106]
 [-0.07255054  0.05987133  1.50584264  0.7650579 ]
 [-0.51488329  0.96040972 -0.24869063 -0.4180812 ]
 [ 0.82240373 -1.88700499 -1.33226594 -0.51072195]
 [-1.53623058  0.69569342 -0.63058873 -1.3262558 ]]


### Problem 6: Conditional Operations
Create an array of 20 random integers between -10 and 10. Then:

1. Replace negative values with 0
2. Replace positive values greater than 5 with 5 (clip maximum)
3. Count how many zeros are in the final array

In [7]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(-10, 10, size = 20)
original_arr = arr.copy()
print(f"Original array: \n{arr}")

# Replace negative values with 0
arr[arr < 0] = 0
print(f"negateves repalaced arr: \n{arr}")
arr[arr > 5] = 5
print(f"grater than 5 replaced arr: \n{arr}")
zero_count = np.count_nonzero(arr == 0)
print(f"Number of zeros in the final array is: {zero_count}")

Original array: 
[ -4   9   4   0  -3  -4   8   0   0  -7  -3  -8  -9   1  -5  -9 -10   1
   1   6]
negateves repalaced arr: 
[0 9 4 0 0 0 8 0 0 0 0 0 0 1 0 0 0 1 1 6]
grater than 5 replaced arr: 
[0 5 4 0 0 0 5 0 0 0 0 0 0 1 0 0 0 1 1 5]
Number of zeros in the final array is: 13


### Problem 7: Matrix Operations
Create two 3x3 matrices A and B with random integers from 1 to 9. Then:

1. Compute the matrix multiplication A @ B
2. Find the determinant of the result
3. Check if the result is invertible (determinant ≠ 0)

In [8]:
import numpy as np
np.random.seed(42)
A = np.random.randint(1, 9, size = (3, 3))
B = np.random.randint(1, 9, size = (3, 3))

print(f"A: \n{A}")
print(f"B: \n{B}")

# Compute the matrix multiplication A @ B
C = A @ B
print(f"A @ B: \n{C}")
# Find the determinant of the result
det_c = np.linalg.det(C)
print(f"The determinant of A @ B is: {det_c}")
if det_c == 0:
    print("The result is not invertible")
else:
    print("The result is invertible")

A: 
[[7 4 5]
 [7 3 8]
 [5 5 7]]
B: 
[[2 3 7]
 [3 3 8]
 [5 4 8]]
A @ B: 
[[ 51  53 121]
 [ 63  62 137]
 [ 60  58 131]]
The determinant of A @ B is: -758.999999999999
The result is invertible


### Problem 8: Data Cleaning
Create an array: [1.2, 2.5, np.nan, 4.1, np.nan, 6.8, 7.2, np.nan, 9.1, 10.0]

1. Count the number of NaN values
2. Calculate the mean ignoring NaN values
3. Replace NaN values with the mean of non-NaN values

In [9]:
import numpy as np
arr = np.array([1.2, 2.5, np.nan, 4.1, np.nan, 6.8, 7.2, np.nan, 9.1, 10.0])
original_arr = arr.copy()
print(f"Original array: \n{original_arr}")

# Count the number of NaN values
nan_count = np.sum(np.isnan(arr))
print(f"The number of NaN values is: {nan_count}")

mean = np.nanmean(arr)
print(f"The mean after ignoring NaN is: {mean}")
# Replace NaN values with the mean of non-NaN values
arr[np.isnan(arr)] = mean
print(f"The array after NaN values replaced with mean: \n{arr}")

Original array: 
[ 1.2  2.5  nan  4.1  nan  6.8  7.2  nan  9.1 10. ]
The number of NaN values is: 3
The mean after ignoring NaN is: 5.8428571428571425
The array after NaN values replaced with mean: 
[ 1.2         2.5         5.84285714  4.1         5.84285714  6.8
  7.2         5.84285714  9.1        10.        ]


### Problem 9: Pattern Creation
Create a 8x8 checkerboard pattern where:

1. Even positions (i+j is even) have value 0
2. Odd positions (i+j is odd) have value 1
3. Do this without using loops.

In [10]:
import numpy as np
arr = np.ones((8, 8))
arr[::2, [0, 2, 4, 6]] = 0
arr[1::2, [1, 3, 5, 7]] = 0
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### Problem 10: Advanced Indexing
Create a 5x5 matrix with values from 1 to 25. Then:

1. Extract elements at positions (0,0), (1,2), (3,4), and (4,1) using fancy indexing
2. Create a boolean mask to select all elements in the border (first/last row/column)
3. Replace all border elements with 99

In [11]:
import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
original_arr = arr.copy()
print(f"Original array: \n{original_arr}")
# Extract elements at positions (0,0), (1,2), (3,4), and (4,1) using fancy indexing
ext = arr[[0, 1, 3, 4], [0, 2, 4, 1]]
print(f"elements at positions (0,0), (1,2), (3,4), and (4,1): {ext}")

arr[:, -1]

Original array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
elements at positions (0,0), (1,2), (3,4), and (4,1): [ 1  8 20 22]


array([ 5, 10, 15, 20, 25])