# 1. Numpy basics and creation of arrays 

In [1]:
# Import NumPy library as 'np' alias
import numpy as np

## Creating arrays

In [2]:
# Craete an array
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Creating 3 x 4 array of zeros
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#  2 x 3 array of ones
ones = np.ones((2, 2))
ones

array([[1., 1.],
       [1., 1.]])

In [6]:
# Create 3 x 3 uninitialized array
empty = np.empty((3, 3))
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.69120688e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [7]:
# Craete 3 x 3 array filled with 5
full = np.full(shape = (3, 3), fill_value = 5)
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
# Using ranges
arange = np.arange(0, 20, 2)
arange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
linspace = np.linspace(0, 10, 20)
linspace

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [10]:
# Random arrays
random_float = np.random.random_sample((2, 3))
random_float

array([[0.38858213, 0.29472524, 0.72042888],
       [0.24323604, 0.78524027, 0.60185175]])

In [11]:
random_int = np.random.randint(1, 10, (2, 3))
random_int

array([[1, 8, 3],
       [6, 2, 6]], dtype=int32)

## Key Attributes

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# dimension of arr
print(f"shape: {arr.shape}")
# Total number of elements
print(f"size: {arr.size}")
# Number of dimensions
print(f"dimension: {arr.ndim}")
# Data type
print(f"Data type: {arr.dtype}")

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
size: 6
dimension: 2
Data type: int64


# Data Types

In [13]:
# Specify data types
int_arr = np.array([1, 2, 3], dtype = np.int64)
int_arr

array([1, 2, 3])

In [14]:
float_arr = np.array([1, 2, 3], dtype = np.float64)
float_arr

array([1., 2., 3.])

In [15]:
# Convert data types
arr_float = np.array([1.4, 4.5, 6.9])
int_arr = arr_float.astype(np.int64)
int_arr

array([1, 4, 6])

# Array indexing and slicing

In [16]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# Basic indexing
# extract 7(row 1, column 2)
arr[1, 2]

np.int64(7)

In [17]:
# Extract [1, 2, 3, 4] (first row)
arr[0]

array([1, 2, 3, 4])

In [18]:
# Slicing
# Extract first 2 rows, columns 1-2
arr[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [19]:
# extract row 1 onwards and first 2 columns
arr[1:, :2]

array([[ 5,  6],
       [ 9, 10]])

In [20]:
# Last column
arr[:, -1]

array([ 4,  8, 12])

In [21]:
# Step slicing
# every 2nd row and column
arr[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [22]:
# Boolean indexing
mask = arr > 5
arr[mask]

array([ 6,  7,  8,  9, 10, 11, 12])

In [23]:
# Fancy indexing
indices = [0, 2]
arr[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## Practice indexing and slicing

### Setup

In [24]:
v = np.arange(10)
print(f"v: \n{v}")
A = np.arange(12).reshape(3, 4)
print(f"A: \n{A}")

v: 
[0 1 2 3 4 5 6 7 8 9]
A: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Basic Indexing

In [25]:
# 1D indexing
v[0]

np.int64(0)

In [26]:
v[-1]

np.int64(9)

In [27]:
# 1D slicing
v[2:7:2]

array([2, 4, 6])

In [28]:
v[::3]

array([0, 3, 6, 9])

In [29]:
# Multi-dim indexing
print(A)
A[2, 3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(11)

In [30]:
A[:, 2]

array([ 2,  6, 10])

### Views and Copies
- Slicing returns a view (where possible). Modifying the slice modifies the original array.

In [31]:
s = A[:, :2]
print(f"s before: \n{s}")
s[0, 0] = 999
print(f"s after: \n{s}")
print(f"A after: \n{A}")

s before: 
[[0 1]
 [4 5]
 [8 9]]
s after: 
[[999   1]
 [  4   5]
 [  8   9]]
A after: 
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


- Advanced (integer/fancy) indexing returns a copy.

In [32]:
i = A[1]
i[0] = -999
A

array([[ 999,    1,    2,    3],
       [-999,    5,    6,    7],
       [   8,    9,   10,   11]])

1. Create an array v = np.arange(20).
- Extract the first 5 elements.
- Extract every second element starting from index 2.
- Reverse the array.

In [33]:
v = np.arange(20)
# Extract the first 5 elements
print(v[:5])
# Extract every second element starting from index 2.
print(v[2::2])
# Reverse the array.
print(v[::-1])

[0 1 2 3 4]
[ 2  4  6  8 10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


2. Given A = np.arange(12).reshape(3,4), extract:
- Row 1.
- Column 2.
- Submatrix consisting of rows 0–1 and columns 1–3.

In [34]:
A = np.arange(12).reshape(3, 4)
# Row 1
print(A[1])
# Column 2
print(A[:, 2])
# Submatrix consisting of rows 0–1 and columns 1–3.
print(A[:2, 1:])

[4 5 6 7]
[ 2  6 10]
[[1 2 3]
 [5 6 7]]


3. From B = np.arange(27).reshape(3,3,3), select:
- The last “slice” along axis 0.
- All elements at index 2 along the last axis. 

In [35]:
B = np.arange(27).reshape(3, 3, 3)
# The last “slice” along axis 0.
print(B[-1, :, :])
# All elements at index 2 along the last axis.
print(B[:, :, 2])

[[18 19 20]
 [21 22 23]
 [24 25 26]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


1. Create x = np.arange(10).
- Make a slice y = x[2:7]. Change y[0] = -99. What happens to x? Why?
- Now try z = x[[2,3,4]]. Change z[0] = -88. What happens to x? Why?

In [36]:
x = np.arange(10)
print(f"x before: \n{x}")

y = x[2:7]
print(f"y before: \n{y}")
y[0] = -99
print(f"x after: \n{x}")
# Because it is slicing it returns view

x before: 
[0 1 2 3 4 5 6 7 8 9]
y before: 
[2 3 4 5 6]
x after: 
[  0   1 -99   3   4   5   6   7   8   9]


In [37]:
print(f"x before: \n{x}")
z = x[[2, 3, 4]]
z[0] = -88
print(f"x after: \n{x}")
# Because it is fancy indexing it returns copy

x before: 
[  0   1 -99   3   4   5   6   7   8   9]
x after: 
[  0   1 -99   3   4   5   6   7   8   9]


2. Given A = np.arange(16).reshape(4,4), try:
- S = A[:2, :2] → modify S[0,0].
- F = A[[0,2], [1,3]] → modify F[0].
- Predict which one changes A and confirm.

In [38]:
A = np.arange(16).reshape(4, 4)
print(f"A before: \n{A}")

# S = A[:2, :2] → modify S[0,0].
S = A[:2, :2]
S[0, 0] = -999
print(f"A after: \n{A}")

# F = A[[0,2], [1,3]] → modify F[0]
F = A[[0, 2], [1, 3]]
F[0] = -888
print(f"A after: \n{A}")

# S changes A because it is slicing

A before: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
A after: 
[[-999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]
A after: 
[[-999    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]


3. v = np.arange(10)
    - Extract only even numbers.
    - Replace all values greater than 5 with 100.

4. Given A = np.arange(12).reshape(3,4):
    - Mask all elements divisible by 3.
    - Replace those elements with -1.

5. Combine conditions:
    - From v = np.arange(20), select numbers greater than 5 and less than 12.

In [39]:
v = np.arange(10)

# Extract only even numbers.
even_v = v[v % 2 == 0]
print(even_v)

# Replace all values greater than 5 with 100.
v[v > 5] = 100
print(v)



[0 2 4 6 8]
[  0   1   2   3   4   5 100 100 100 100]


In [40]:
A = np.arange(12).reshape(3, 4)
mask = A % 3 == 0
print(A[mask])
A[mask] = -1
print(A)

[0 3 6 9]
[[-1  1  2 -1]
 [ 4  5 -1  7]
 [ 8 -1 10 11]]


In [41]:
v = np.arange(20)
m = (v > 5) & (v < 12)
print(v[m])

[ 6  7  8  9 10 11]


6. You have temps = np.array([30, 25, 27, 40, 20, 15, 35]) (daily temperatures).
- Extract temps above 30.
- Replace temps below 20 with the average temperature.

7. You have grades = np.array([[80, 90, 70],[60, 75, 85],[95, 100, 90]]).
- Select all grades for the second student.
- Select all grades above 85.
- Replace all grades below 70 with 70.

8. Bonus challenge — create a 10×10 array filled with random integers 0–99.
- Extract the border (first and last rows, first and last columns).
- Extract the 3×3 center.
- Replace all even numbers with -1.

In [42]:
temps = np.array([30, 25, 27, 40, 20, 15, 35])
# Extract temps above 30.
print(temps[temps > 30])
# Replace temps below 20 with the average temperature.
temps_avg = np.average(temps)
temps[temps < 20] = temps_avg
print(temps)

[40 35]
[30 25 27 40 20 27 35]


In [43]:
grades = np.array([[80, 90, 70],
                   [60, 75, 85],
                   [95, 100, 90]])
# Select all grades for the second student.
print(grades[1])
# Select all grades above 85.
print(grades[grades > 65])
# Replace all grades below 70 with 70.
grades[grades < 70] = 70
print(grades)

[60 75 85]
[ 80  90  70  75  85  95 100  90]
[[ 80  90  70]
 [ 70  75  85]
 [ 95 100  90]]


In [44]:
np.random.seed(42)
A = np.random.randint(100, size = (10, 10))
print(A)
# Extract the border (first and last rows, first and last columns).
A[[0, -1],]

[[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]


array([[51, 92, 14, 71, 60, 20, 82, 86, 74, 74],
       [71, 77, 86, 61, 39, 84, 79, 81, 52, 23]], dtype=int32)

# Array Operations

In [45]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Arithmetic operations
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"b / a = {b / a}")
print(f"a ** b = {a ** b}")
print(f"b % a = {b % a}")

a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
b / a = [5.         3.         2.33333333 2.        ]
a ** b = [    1    64  2187 65536]
b % a = [0 0 1 0]


In [46]:
# Comparasion operators
print(a > 2)

[False False  True  True]


In [47]:
# Operations with scalars(broadcasting)
print(f"a + 10 = {a + 10}")
print(f"a x 2 = {a * 2}")

a + 10 = [11 12 13 14]
a x 2 = [2 4 6 8]


In [48]:
A = np.ones((3, 4))
b = np.array([1, 2, 3, 4])

print(A + b)
# Each row gets [1,2,3,4] added.


[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


In [49]:
x = np.arange(3)[:, None]   # shape (3,1)
y = np.arange(4)            # shape (4,)
print(x + y)                # shape (3,4)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [50]:
# Aggregate functions
M = np.arange(12).reshape(3, 4)

print(f"Total = {M.sum()}")
print(f"Total along axis 0 = {M.sum(axis = 0)}")
print(f"Total along axis 1 = {M.sum(axis = 1)}")
print(f"Mean = {M.mean()}")
print(f"Mean along axis 0 = {M.mean(axis = 0)}")
print(f"Mean along axis 1 = {M.mean(axis = 1)}")
print(f"Max = {M.max()}")
print(f"Min = {M.min()}")
print(f"Standard deviation = {M.std()}")

Total = 66
Total along axis 0 = [12 15 18 21]
Total along axis 1 = [ 6 22 38]
Mean = 5.5
Mean along axis 0 = [4. 5. 6. 7.]
Mean along axis 1 = [1.5 5.5 9.5]
Max = 11
Min = 0
Standard deviation = 3.452052529534663


In [51]:
# Matrix operations
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6],
              [7, 8]])
print(f"matrix multiply = \n{x @ y}")
print(f"dot product = \n{np.dot(x, y)}")
print(x.T)

matrix multiply = 
[[19 22]
 [43 50]]
dot product = 
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [52]:
# Universal functions
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [53]:
# Comparasion and logical operators
x = np.array([1, 2, 3, 4])
y = np.array([2, 2, 2, 2])

print(x > y)
print(np.all(x > 0))
print(np.any(x == 3))
print(np.where(x > 2, 1, x))

[False False  True  True]
True
True
[1 2 1 1]


In [54]:
# Advanced
arr = np.array([1,2,3])
print(arr.cumsum())  # [1 3 6]
print(arr.cumprod()) # [1 2 6]

[1 3 6]
[1 2 6]


In [55]:
np.clip(arr, 0, 1)   # restricts values into [0,1]

array([1, 1, 1])

1. Create a 5×5 array of random ints 0–9. Compute row sums and column max values.
2. Normalize an array of shape (n, d) so each column has mean 0 and std 1.
3. Given a = np.array([1,2,3]), compute:
    - Outer product.
    - Dot product.
    - Norm.
4. Build a 4×4 array and set all negative values to 0 (ReLU-style).
5. Simulate softmax for [2.0, 1.0, 0.1] using np.exp and broadcasting.

In [56]:
# Create a 5×5 array of random ints 0–9. Compute row sums and column max values
np.random.seed(42)
arr = np.random.randint(0, 10, size = (5, 5))
print(f"arr = \n{arr}")
print(f"row sums = \n{np.sum(arr, axis = 1)}")
print(f"column max = \n{np.max(arr, axis = 0)}")

arr = 
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]
row sums = 
[26 28 24 18 26]
column max = 
[9 7 9 7 8]


In [57]:
# Normalize an array of shape (n, d) so each column has mean 0 and std 1.
print(f"orginal array: \n{arr}")
print(f"original mean = {np.mean(arr)}")
print(f"original std = {np.std(arr)}")

norm_arr = (arr - np.mean(arr))/np.std(arr)
print(f"Normalized array: \n{norm_arr}")
print(f"normalized mean = {np.mean(norm_arr)}")
print(f"normalized std = {np.std(norm_arr)}")

orginal array: 
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]
original mean = 4.88
original std = 2.4547097588106013
Normalized array: 
[[ 0.45626575 -0.76587466  0.86364589 -0.35849452  0.45626575]
 [ 1.67840617 -1.1732548   0.45626575  0.86364589 -0.35849452]
 [-0.76587466  0.86364589  0.86364589 -1.1732548   0.04888562]
 [-0.35849452 -1.58063493  0.86364589  0.04888562 -1.58063493]
 [-0.35849452 -1.98801507  1.67840617  0.04888562  1.27102603]]
normalized mean = 4.4408920985006264e-17
normalized std = 0.9999999999999998


In [58]:
# Given a = np.array([1,2,3]), compute:
a = np.array([1, 2, 3])
# Outer product
print(f"outer product: \n{np.linalg.outer(a, a)}")
print(f"Dot product: \n{np.dot(a, a)}")
print(f"Norm: \n{np.linalg.norm(a)}")

outer product: 
[[1 2 3]
 [2 4 6]
 [3 6 9]]
Dot product: 
14
Norm: 
3.7416573867739413


In [59]:
# Build a 4×4 array and set all negative values to 0 (ReLU-style).
np.random.seed(42)
arr = np.random.randint(-5, 5, size = (10, 10))
print(f"original: \n{arr}")
new_arr = np.where(arr < 0, 0, arr)
print(f"updated: \n{new_arr}")

original: 
[[ 1 -2  2 -1  1  4 -3  1  2 -1]
 [-2  2  2 -3  0 -1 -4  2  0 -4]
 [-1 -5  4  0  3 -5  4 -3  1 -2]
 [ 3 -3 -1 -3  1 -1  3  1 -4 -2]
 [ 3 -4  4  3  4 -1 -4 -2  1  2]
 [-3 -5 -2 -4  2 -2 -4  0  0  4]
 [-2  0 -4  4 -4  4 -2  2  1  3]
 [ 2 -1 -4 -1  2  4  3  3 -5  3]
 [ 1  3  2 -5  2  2 -3 -5  2 -3]
 [-3 -5 -1  4  1  4  3  1  3  2]]
updated: 
[[1 0 2 0 1 4 0 1 2 0]
 [0 2 2 0 0 0 0 2 0 0]
 [0 0 4 0 3 0 4 0 1 0]
 [3 0 0 0 1 0 3 1 0 0]
 [3 0 4 3 4 0 0 0 1 2]
 [0 0 0 0 2 0 0 0 0 4]
 [0 0 0 4 0 4 0 2 1 3]
 [2 0 0 0 2 4 3 3 0 3]
 [1 3 2 0 2 2 0 0 2 0]
 [0 0 0 4 1 4 3 1 3 2]]


# Array Manipulation

In [60]:
# Reshaping arrays
arr = np.arange(12)
print(arr)
a = arr.reshape(3, 4)
print(f"a: \n{a}")
b = arr.reshape(2, 2, 3)
print(f"b: \n{b}")
c = arr.reshape(2, -1)
print(f"c: \n{c}")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
a: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
c: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [61]:
# Flattening/ravel
a = np.arange(6).reshape(2,3)
print(f"a: \n{a}")
print(f"copy flatten: {a.flatten()}")
print(f"view flatten: {a.ravel()}")

a: 
[[0 1 2]
 [3 4 5]]
copy flatten: [0 1 2 3 4 5]
view flatten: [0 1 2 3 4 5]


In [62]:
# Transpose and Axes swap
A = np.arange(12).reshape(3, 4)
print(f"A: \n{A}")
print(f"A transpose: \n{A.T}")
print(np.swapaxes(A, 0, 1))

A: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A transpose: 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [63]:
# Adding and removing dimensions
a = np.array([1, 2, 3])
print(a[:, None])
print(a[None, :])

[[1]
 [2]
 [3]]
[[1 2 3]]


In [64]:
# Concatenate and stacking
a = a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(f"a: \n{a}")
print(f"b: \n{b}")
print('\n',np.concatenate([a, b]))
print(np.concatenate([a, b], axis = 1))

a: 
[[1 2]
 [3 4]]
b: 
[[5 6]
 [7 8]]

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [65]:
np.stack([a,b], axis=0)  # shape (2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [66]:
# Repeating and Tile
a = np.array([1, 2, 3])
print(np.repeat(a, 2))
print(np.tile(a, 2))

[1 1 2 2 3 3]
[1 2 3 1 2 3]


In [67]:
# Sorting and unique
a = np.array([3, 1, 2, 2,3])
print(np.sort(a))
print(a.sort())
print(np.argsort(a))
print(np.unique(a))

[1 2 2 3 3]
None
[0 1 2 3 4]
[1 2 3]


1. Create a 4×4 array, flatten it, then reshape to 2×8.
2. Stack two 3×3 arrays vertically and horizontally, compare shapes.
3. Split a 6×6 array into 3 equal parts along rows, then along columns.
4. Reorder a 3×4 array columns as [3,1,0,2].
5. Repeat a 1D array [1,2,3] three times as elements, then tile it three times as a full array.

In [68]:
# Create a 4×4 array, flatten it, then reshape to 2×8.
arr = np.arange(16).reshape(4, 4)
print(arr)
new_arr = arr.reshape(2, 8)
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [69]:
# Stack two 3×3 arrays vertically and horizontally, compare shapes.
a = np.zeros((3, 3))
b = np.ones((3, 3))
print(f"a: \n{a}")
print(f"b: \n{b}")
print(f"Vertically stack: \n{np.vstack((a, b))}")
print(f"horizontally stack: \n{np.hstack((a, b))}")

a: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Vertically stack: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
horizontally stack: 
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [70]:
# Split a 6×6 array into 3 equal parts along rows, then along columns.
arr = np.arange(36).reshape(6, 6)
print(f"arr: \n{arr}")
print(np.hsplit(arr, 3)) # along columns
print(np.vsplit(arr, 3)) # along rows

arr: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])]
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])]


In [71]:
# Reorder a 3×4 array columns as [3,1,0,2].
a = np.arange(12).reshape(3, 4)
print(f"a: \n{a}")
reordered_a = a[:, [3, 1, 0, 2]]
print(f"reordered a: \n{reordered_a}")

a: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reordered a: 
[[ 3  1  0  2]
 [ 7  5  4  6]
 [11  9  8 10]]


In [72]:
# Repeat a 1D array [1,2,3] three times as elements, then tile it three times as a full array.
arr = np.array([1, 2, 3])
repated_arr = np.repeat(arr, 3)
tiled_arr = np.tile(arr, 3)
print(f"arr: \n{arr}")
print(f"repeated: \n{repated_arr}")
print(f"Tiled: \n{tiled_arr}")

arr: 
[1 2 3]
repeated: 
[1 1 1 2 2 2 3 3 3]
Tiled: 
[1 2 3 1 2 3 1 2 3]


# Broadcasting

In [73]:
# Scalar with array 
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
result = arr + 10
print(result)

[[11 12 13]
 [14 15 16]]


In [74]:
# 1D array with 2D array
arr_2d = np.array([[1, 2, 3], 
                [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [75]:
# Column vector with row vector
col = [[1],
       [2],
       [3]]
row = np.array([10, 20, 30])
result = col + row
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


# Linear Algebra Opeartions

In [76]:
# Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

dot_product = np.dot(A, B)
dot_product_alt = A @ B

print(f"A x B: \n{dot_product}")

A x B: 
[[19 22]
 [43 50]]


In [77]:
# Vector operations
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
dot_vectors = np.dot(v1, v2)
print(f"Dot product of v1 and v2 is {dot_vectors}")

Dot product of v1 and v2 is 32


In [78]:
# Linear algebra functions
A = np.array([[1, 2],
              [3, 4]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eigenvals = np.linalg.eigvals(A)

print(f"Determinant of A = {det}")
print(f"Inverse of A = \n{inv}")
print(f"Eigenvalues of A = {eigenvals}")

Determinant of A = -2.0000000000000004
Inverse of A = 
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues of A = [-0.37228132  5.37228132]


# Statistical Operations

In [79]:
data = np.arange(1, 13).reshape(3, 4)
print(f"Data: \n{data}")

# Basic statistics
mean_all = np.mean(data)
mean_axis0 = np.mean(data, axis = 0)
mean_axis1 = np.mean(data, axis = 1)

print(f"overall mean = {mean_all}")
print(f"mean along rows = {mean_axis1}")
print(f"mean along columns= {mean_axis0}")

Data: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
overall mean = 6.5
mean along rows = [ 2.5  6.5 10.5]
mean along columns= [5. 6. 7. 8.]


In [80]:
np.std(data)

np.float64(3.452052529534663)

In [81]:
np.var(data)

np.float64(11.916666666666666)

In [82]:
np.median(data)

np.float64(6.5)

In [83]:
np.percentile(data, 75)

np.float64(9.25)

In [84]:
np.corrcoef(data)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Working with Missing Data

In [85]:
# NaN handling
data_with_nan = np.array([1, 2, np.nan, 4, 5])
data_with_nan

array([ 1.,  2., nan,  4.,  5.])

In [86]:
is_nan = np.isnan(data_with_nan)
is_nan

array([False, False,  True, False, False])

In [87]:
has_nan = np.any(np.isnan(data_with_nan))
has_nan

np.True_

In [88]:
clean_data = data_with_nan[~np.isnan(data_with_nan)]
clean_data

array([1., 2., 4., 5.])

In [89]:
np.sum(data_with_nan)

np.float64(nan)

In [90]:
# NaN aware functions
np.nanmean(data_with_nan)

np.float64(3.0)

In [91]:
np.nansum(data_with_nan)

np.float64(12.0)

np.s