In [1]:
import numpy as np

In [2]:
f = np.genfromtxt('winequality-red.csv', delimiter = ',', dtype = float, skip_header = 1)

In [3]:
print(f)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [4]:
# Let's print the fixed acidity level of the red wine which is the first column
print(f[:, 0])

[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [5]:
# What if we want to preserve the rows of each value
print(f[:, 0:1])

[[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [6]:
# lets display rhe first three columns of the dataset
print(f[:, :3])

[[7.4   0.7   0.   ]
 [7.8   0.88  0.   ]
 [7.8   0.76  0.04 ]
 ...
 [6.3   0.51  0.13 ]
 [5.9   0.645 0.12 ]
 [6.    0.31  0.47 ]]


In [7]:
# What if we want just not consequetive columns?
print(f[:, [0, 2, 4]])   # print column 0, 2, and 4

[[7.4   0.    0.076]
 [7.8   0.    0.098]
 [7.8   0.04  0.092]
 ...
 [6.3   0.13  0.076]
 [5.9   0.12  0.075]
 [6.    0.47  0.067]]


In [8]:
# let's do some data anaysis on quality of wine which is the ast column of the the dataset
quality = f[:, -1]
print('Maximum quality:', np.max(quality))
print('Minimum quality:', np.min(quality))
print('Average quality:', np.mean(quality))

Maximum quality: 8.0
Minimum quality: 3.0
Average quality: 5.6360225140712945


In [9]:
# Alcohol amount
alcohol = f[:, -2]
print('Maximum alcohol amount:', np.max(alcohol))
print('Minimum alcohol amount:', np.min(alcohol))
print('Average alcohol amount:', np.mean(alcohol))

Maximum alcohol amount: 14.9
Minimum alcohol amount: 8.4
Average alcohol amount: 10.422983114446529
