## 1. Vector Norms & Distance
Task: Compute the Euclidean norm and distance between two vectors.

In [1]:
import numpy as np
u = np.array([3, -4, 12])


np.linalg.norm(u)

np.float64(13.0)

In [2]:
u = np.array([1, 2, 3])
v = np.array([4, 6, 8])

np.linalg.norm(u-v)

np.float64(7.0710678118654755)

## 2. Inner Product & Angle Between Vectors
Task: Compute the dot product and angle between two vectors.

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, -5, 6])

dot_pro = np.dot(a, b)
print(f"The dot product of a and b is: {dot_pro}")

angle = np.arccos(np.dot(a, b)/(np.linalg.norm(a) * np.linalg.norm(b)))
print(f"The angle between vecator a and b is: {np.rad2deg(angle)}")

The dot product of a and b is: 12
The angle between vecator a and b is: 68.56244696639715


## 3. Checking for Orthogonality
Task: Verify if two vectors are orthogonal.

In [4]:
def are_ortho(x, y):
    if np.dot(x, y) == 0:
        return "Orthogonal"
    else:
        return "Not orthogonal"

u = np.array([1, -1, 2])
v = np.array([2, 2, -1])

are_ortho(u, v)

'Not orthogonal'

## 4. Orthogonal Projection onto a Line
Task: Find the orthogonal projection of v onto a given line defined by vector u.

In [5]:
v = np.array([3, 4, 5])
u = np.array([1, 2, 3])

proj_v_onto_u = (np.dot(u, v)/np.dot(u, u)) * u
print(f"The projection of v onto u is: {proj_v_onto_u}")

The projection of v onto u is: [1.85714286 3.71428571 5.57142857]


## 5. Rotation in 2D Space
Task: Rotate a vector by 45 degrees using a rotation matrix.

In [6]:
v = np.array([1, 0])
a = np.pi/4
R = np.array([[np.cos(a), -np.sin(a)],
              [np.sin(a), np.cos(a)]])

R @ v

array([0.70710678, 0.70710678])

## 6. Gram-Schmidt Orthogonalization
Task: Convert a set of linearly independent vectors into an orthonormal basis

In [7]:
v1 = np.array([1, 1, 0])
v2 = np.array([1, 0, 1])

u1 = v1
q1 = u1/np.linalg.norm(u1)

u2 = v2 - (np.dot(v2, q1) * q1)
q2 = u2/np.linalg.norm(u2)

q1

array([0.70710678, 0.70710678, 0.        ])

## 7. Reflection Over a Line in 2D
Task: Reflect a vector over the x-axis.

In [8]:
def reflect_on_x(v):
    R = np.array([[1, 0],
                  [0, -1]])
    return R @ v


v = np.array([3, 5])
reflect_on_x(v)

array([ 3, -5])

## 8. Equation of a Plane in 3D
Task: Find the equation of a plane that passes through a given point and is orthogonal to a given normal vector.

In [9]:
def line(v, p):
    d = np.dot(v, p)
    return f"{v[0]}x + {v[1]}y + {v[2]}z = {d}"

point = np.array([2, 5, 4])
v = np.array([1, -2, 4])

line(v, point)

'1x + -2y + 4z = 8'

## 9. Transformation Matrix for Projection
Task: Compute the transformation matrix for projecting vectors onto a given line spanned by vector u.

In [10]:
u = np.array([[3, 4]])
(u.T @ u)/(u @ u.T)

array([[0.36, 0.48],
       [0.48, 0.64]])